zen-panel-ui-current-profile-text = 當前設定檔
unified-extensions-description = 擴充功能用於為 { -brand-short-name } 帶來更多功能。
tab-context-zen-reset-pinned-tab = 
    .label = 重置釘選的分頁
    .accesskey = R
tab-context-zen-add-essential = 
    .label = 添加到 Essentials
    .accesskey = E
tab-context-zen-remove-essential = 
    .label = 從 Essentials 移除
    .accesskey = R
tab-context-zen-replace-pinned-url-with-current = 
    .label = 將釘選的網址換成目前的網址
    .accesskey = C
tab-zen-unload = 
    .label = 卸載分頁
    .accesskey = U
zen-tabs-unloader-tab-actions = 
    .label = 卸載分頁操作
    .accesskey = T
tab-zen-prevent-unload = 
    .label = 避免卸載分頁
    .accesskey = P
tab-zen-ignore-unload = 
    .label = 允許卸載分頁
    .accesskey = I
zen-themes-corrupted = 你的 { -brand-short-name } 模組已損壞，已重置為預設的主題
zen-shortcuts-corrupted = 你的 { -brand-short-name } 捷徑已損壞，已重置
zen-panel-ui-gradient-generator-opacity-text = 對比度
zen-panel-ui-gradient-generator-texture-text = 材質
zen-panel-ui-gradient-generator-custom-color = 自訂顏色
zen-panel-ui-gradient-generator-saved-message = 漸層儲存成功！
zen-copy-current-url-confirmation = 網址已複製到剪貼簿
zen-rice-share-name = 
    .placeholder = Rice 名稱
zen-rice-share-author = 來自
zen-rice-share-author-input = 
    .placeholder = 你的名字
zen-rice-share-cancel = Cancel
zen-rice-share-save = 分享
zen-rice-share-include-userchrome = 
    .label = 包含 zen window styles (userChrome.css)
zen-rice-share-include-usercontent = 
    .label = 包含網站的風格 (userContent.css)
zen-rice-share-include-mods = 
    .label = 包含開啟的模組
zen-rice-share-include-mod-prefs = 
    .label = 包含模組的設定
zen-rice-share-include-preferences = 
    .label = 包含布局的設定
zen-rice-share-include-workspace-themes = 
    .label = 包含工作空間的漸層主題
zen-rice-share-success = 成功創立了一個Rice!
zen-rice-share-success-link = Rice的分享連結
zen-rice-share-accept = 接受
zen-rice-share-notice = 在分享之前，請先了解什麼是 Rice 
# note: Do not translate the "<br/>" tags in the following string
zen-rice-share-notice-description =
    A Rice is a collection of customizations that can be shared with others.<br/>
    This includes your window styles, website styles, enabled mods, mod preferences, layout preferences, and workspace gradient themes.<br/>
    By sharing a Rice, you are sharing all of these customizations with others. Please be mindful of what you share.
zen-learn-more-text = 了解更多
zen-rice-share-include = 輸出選項
appmenu-zen-share-rice = 
    .label = 分享 Zen Rice
zen-close-label = 關閉
